services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    Lupcom\RapidSkeletonBundle\Controller\ContentElement\:
        resource: ../src/Controller/ContentElement
        tags: ['controller.service_arguments']
        public: true

    Lupcom\RapidSkeletonBundle\Controller\Backend\:
        resource: ../src/Controller/Backend
        tags: ['controller.service_arguments']
        public: true
